name: build

on:
  push:
    branches: [ "master" ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3

    - name: build docker image
      run: docker build -t build .

    - name: prepare
      run: cd lib && make prepare && cd ..

    - name: build in docker image
      run: docker run -v $PWD:/work --rm build bash -c "cd /work && make"

    - name: upload artifacts
      uses: actions/upload-artifact@v4
      with:
        path: |
          linux*.tar.gz
          win32*.zip

  release:
    needs: [ build ]
    runs-on: ubuntu-latest
    steps:
    - name: download artifacts 2
      uses: actions/download-artifact@v4
      with:
        path: .

    - name: release
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      run: wget -c https://github.com/probonopd/uploadtool/raw/master/upload.sh && bash upload.sh artifact/*
